[
{ 'id': 00,
  'name': 'Дворцовая площадь.',
  'task': 'Старт ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.939167,30.315833] },
{ 'id': 11,
  'name': 'Пл. Декабристов ',
  'task': 'Дерево на участке напротив д. 2 по Конногвардейскому бульвару',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93576,30.30249] },
{ 'id': 12,
  'name': 'Румянцевский сад ',
  'task': 'Участок ограды со стороны д. 2',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93911,30.29267] },
{ 'id': 13,
  'name': 'Стрелка В.О. ',
  'task': 'Дерево',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro"],
  'coordinates': [59.94431,30.30694] },
{ 'id': 14,
  'name': 'Северо-Западный угол Марсова поля ',
  'task': 'Дерево ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.94455,30.32859] },
{ 'id': 15,
  'name': '2-й Садовый мост ',
  'task': 'Участок ограды рядом с мостом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.94166,30.33019] },
{ 'id': 16,
  'name': 'Восточная часть пл. Искусств ',
  'task': 'Дерево',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93701,30.33303] },
{ 'id': 17,
  'name': 'Старый сад ',
  'task': 'Участок ограды со стороны Казанского собора',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93442,30.32288] },
{ 'id': 18,
  'name': 'Наб. р. Мойки д. 54 ',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93280,30.31591] },
{ 'id': 20,
  'name': 'Юго-западная оконечность Заячего острова',
  'task': 'Дерево',
  'categories': ["run-light", "run-pro"],
  'coordinates': [59.94837,30.30997] },
{ 'id': 21,
  'name': 'пл. Ломоносова, д.2',
  'task': 'Столб',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.92938,30.33417] },
{ 'id': 22,
  'name': 'Наб. р. Фонтанки, д. 30',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93865,30.34344] },
{ 'id': 23,
  'name': 'Гороховая ул., д. 41',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.92890,30.32106] },
{ 'id': 24,
  'name': '4 линия В.О., д. 39',
  'task': 'Дерево в сквере рядом с домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.94542,30.27963] },
{ 'id': 26,
  'name': 'наб. Адмиралтейского канала, д. 31',
  'task': 'Участок ограды напротив дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.92976,30.28645] },
{ 'id': 27,
  'name': 'Угол ул. Блохина и Храмова переулка',
  'task': 'Участок ограды',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.95242,30.29435] },
{ 'id': 30,
  'name': 'Остановка троллейбусов №№ 3,8,15 «Ул.Жуковского» от Невского пр.',
  'task': 'Участок ограды рядом с остановкой',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93489,30.34776] },
{ 'id': 32,
  'name': 'Бульвар на Петровской набережной недалеко от крейсера «Аврора»',
  'task': 'Дерево',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.95424,30.33650] },
{ 'id': 33,
  'name': 'Ограда Спасо-Преображенского собора',
  'task': 'Восточная часть',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.94300,30.35332] },
{ 'id': 34,
  'name': 'Б. Посадская ул., д. 10',
  'task': 'Дерево рядом с домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.95863,30.32387] },
{ 'id': 35,
  'name': '15 линия В.О., д. 74',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.94535,30.26225] },
{ 'id': 36,
  'name': 'Малая Подъяческая ул., д. 3',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.92586,30.30159] },
{ 'id': 37,
  'name': '14 линия В.О., д. 1а',
  'task': 'Дерево напротив дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93417,30.27582] },
{ 'id': 38,
  'name': 'Клинский пр., д. 9',
  'task': 'Дерево в сквере напротив дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.91571,30.32532] },
{ 'id': 39,
  'name': 'Ул. Даля, д. 10',
  'task': 'Дерево рядом с домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.96919,30.29231] },
{ 'id': 40,
  'name': 'Угол Клинической ул. и ул. Академика Лебедева',
  'task': 'Дерево',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.95537,30.35057] },
{ 'id': 41,
  'name': '2-й Каменноостровский мост',
  'task': 'Дерево рядом с мостом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.98183,30.29380] },
{ 'id': 42,
  'name': 'Таврическая ул., д. 21',
  'task': 'Ограда сада напротив дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.94479,30.37813] },
{ 'id': 43,
  'name': 'Наб. реки Фонтанки, д. 112',
  'task': 'Дерево в сквере рядом с домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.92043,30.31533] },
{ 'id': 44,
  'name': 'Ул. Марата, д. 81',
  'task': 'Дерево во дворе дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.91982,30.33881] },
{ 'id': 45,
  'name': 'Озерной пер., д. 8',
  'task': 'Дерево рядом с домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93808,30.36277] },
{ 'id': 46,
  'name': 'Лахтинская ул., д. 19',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.96350,30.29856] },
{ 'id': 47,
  'name': 'Лиговский пр., д. 101',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.92231,30.35478] },
{ 'id': 49,
  'name': '7-я Красноармейская ул., д. 26 ',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.91153,30.30992] },
{ 'id': 50,
  'name': 'пл. Старого театра ',
  'task': 'Столб',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.97675,30.27556] },
{ 'id': 51,
  'name': 'Сквер на углу 8-й Советской ул. и Старорусской ул ',
  'task': 'Дерево',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93302,30.38274] },
{ 'id': 52,
  'name': 'ул. Ак. Павлова, д. 3 ',
  'task': 'Столб',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.97589,30.32022] },
{ 'id': 53,
  'name': 'Покровский сквер на пл. Тургенева ',
  'task': 'Участок ограды в западной части',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.91850,30.28914] },
{ 'id': 54,
  'name': 'Смольный пр., д. 15 ',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.94442,30.39697] },
{ 'id': 55,
  'name': 'Ж.д пл. «Боровая» ',
  'task': 'Участок ограды в северной части платформы',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.90614,30.33833] },
{ 'id': 57,
  'name': 'Ново-Кирпичный мост',
  'task': 'Ограда моста с южной стороны',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.91365,30.36188] },
{ 'id': 59,
  'name': 'Северо-восточная часть сада «Василеостровец»',
  'task': 'Участок ограды',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93587,30.25430] },
{ 'id': 60,
  'name': 'Ул. Опочинина, д. 7',
  'task': 'Дерево напротив дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.92770,30.24074] },
{ 'id': 61,
  'name': '2-й Парковый мост ',
  'task': 'Дерево недалеко от моста',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.96842,30.25127] },
{ 'id': 62,
  'name': 'Изгиб пр. Пархоменко в районе д. 39',
  'task': 'Столб',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.99767,30.35405] },
{ 'id': 63,
  'name': 'ПКиО им. Бабушкина',
  'task': 'Участо ограды со стороны трамвайного кольца',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.88270,30.44405] },
{ 'id': 65,
  'name': 'Республиканская ул., д. 23',
  'task': 'Дерево напротив дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.93355,30.41436] },
{ 'id': 66,
  'name': 'Юго-западная оконечность Митрополического сада',
  'task': 'Дерево',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.91797,30.38161] },
{ 'id': 69,
  'name': 'М.Митрофаньевская ул., д. 4',
  'task': 'Дерево',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.89616,30.31571] },
{ 'id': 71,
  'name': 'Пр. Металлистов, д. 4',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.94363,30.41972] },
{ 'id': 73,
  'name': 'Ж.д пл. «Воздухоплавательный парк»',
  'task': 'Дерево рядом с платформой «От Петербурга»',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.89175,30.34556] },
{ 'id': 74,
  'name': 'Наб. Бумажного канала, д. 18а',
  'task': 'Дерево напротив дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.90284,30.26942] },
{ 'id': 75,
  'name': 'Ул. Победы, д. 15',
  'task': 'Водосточная труба',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.86066,30.31976] },
{ 'id': 77,
  'name': 'Пр. Энгельса, д. 22',
  'task': 'Водосточная труба',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [60.00228,30.32747] },
{ 'id': 78,
  'name': 'Наб. Черной речки, д. 26',
  'task': 'Столб напротив дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.98889,30.28733] },
{ 'id': 79,
  'name': 'Литовская ул., д. 2',
  'task': 'Дерево рядом с домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.97734,30.34139] },
{ 'id': 80,
  'name': 'Угол Адмиральского пр. и Морской наб.',
  'task': 'Столб',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.96056,30.23019] },
{ 'id': 81,
  'name': 'Парк «Сосновка». Стадион в глубине парка напротив дд. 82-90 по пр. М. Тореза',
  'task': 'Дерево на краю стадиона, ближайшем к проспекту',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.01824,30.34000] },
{ 'id': 82,
  'name': 'Трамвайное кольцо «Завод имени Ленина»',
  'task': 'Дерево внутри кольца',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.90567,30.41862] },
{ 'id': 83,
  'name': 'ул. Антонова-Овсеенко, д. 3',
  'task': 'Дерево в парке Строителей напротив дома',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.90588,30.45794] },
{ 'id': 85,
  'name': 'Изгиб Броневой ул. в районе дд. 8 и 12',
  'task': 'Дерево',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.87544,30.28389] },
{ 'id': 86,
  'name': 'Пересечение ул. Фучика и Бухарестской ул.',
  'task': 'Столб на остановке автобусных маршрутов 59 и 74',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.87868,30.37247] },
{ 'id': 88,
  'name': 'Бассейная ул., д. 89',
  'task': 'Остановочный павильон рядом с домом',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.86506,30.35592] },
{ 'id': 89,
  'name': 'Пр. Мечникова, д. 18',
  'task': 'Дерево рядом с домом',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.98644,30.40393] },
{ 'id': 90,
  'name': 'Пересечение Планерной ул. и Долгоозерной ул.',
  'task': 'Опора ЛЭП у южной части пруда недалеко от пересечения',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.01345,30.23163] },
{ 'id': 91,
  'name': 'ул. Вавиловых, д. 5 к. 1',
  'task': 'Дерево рядом с домом',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.01804,30.38805] },
{ 'id': 92,
  'name': 'Березовая роща в районе ж.д. пл «Яхтенная»',
  'task': 'Береза',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.99237,30.21934] },
{ 'id': 93,
  'name': 'Ул. Маршала Тухачевского, д. 31',
  'task': 'Столб на троллейбусной остановке напротив дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.97089,30.42296] },
{ 'id': 94,
  'name': 'Пруд рядом с д. 3 к. 1 по Дачному пр.',
  'task': 'Дерево на берегу пруда',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.84950,30.23849] },
{ 'id': 95,
  'name': 'Трамвайное кольцо «Пр. Славы»',
  'task': 'Дерево к северу от выезда с кольца',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.85731,30.39524] },
{ 'id': 96,
  'name': 'Угол ул. Лопатина и ул. Подвойского',
  'task': 'Столб',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.91908,30.50169] },
{ 'id': 98,
  'name': 'Свердловская наб., д. 40',
  'task': 'Ограда',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro"],
  'coordinates': [59.95851,30.40011] }]