[
{ 'id': 00,
  'name': 'Дворцовая площадь.',
  'task': 'Старт ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.939167,30.315833] },
{ 'id': 10,
  'name': 'Прачечный мост',
  'task': 'Столбик с названием моста со стороны Летнего сада',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.94767,30.33614] },
{ 'id': 11,
  'name': 'Угол Замковой ул. и наб. р. Фонтанки',
  'task': 'Ограда мостика',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.94010,30.33989] },
{ 'id': 12,
  'name': 'Пл. Островского, д. 6. ',
  'task': 'Столб знака "Пешеходный переход" напротив дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.93120,30.33709] },
{ 'id': 13,
  'name': 'Мучной пер., д. 3',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.93039,30.32171] },
{ 'id': 14,
  'name': 'Гражданская ул., д. 1',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.92880,30.31510] },
{ 'id': 16,
  'name': 'Пересечение ул. Куйбышева и Каменноостровского пр.',
  'task': 'Остановочный павильон на нечетной стороне ул. Куйбышева',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.95344,30.32376] },
{ 'id': 17,
  'name': 'Ул. Репина, д. 27',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro"],
  'coordinates': [59.94219,30.28652] },
{ 'id': 18,
  'name': 'Пер. Пирогова, д. 19',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.92884,30.30128] },
{ 'id': 20,
  'name': 'Пантелеймоновский мост (мост Пестеля)',
  'task': 'Участок ограды со стороны Летнего сада',
  'categories': ["run-light", "run-pro"],
  'coordinates': [59.94215,30.33769] },
{ 'id': 21,
  'name': 'Наб. р. Фонтанки, д. 31',
  'task': 'Участок ограды набережной напротив здания',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.93231,30.34200] },
{ 'id': 22,
  'name': 'Ул. Союза печатников, д. 21',
  'task': 'Заборчик перед домом со стороны Мастерской ул.',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.92305,30.28839] },
{ 'id': 23,
  'name': '8-я линия В.О., д. 59',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.94418,30.27410] },
{ 'id': 24,
  'name': 'Фурштатская ул., д. 12',
  'task': 'Вход в Консультационно-образовательный центр "Путь к здоровью"',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.94534,30.35210] },
{ 'id': 25,
  'name': 'Ул. Яблочкова, д. 22/3',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro"],
  'coordinates': [59.95136,30.29671] },
{ 'id': 26,
  'name': 'Мал. Гребецкая ул., д. 3',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.95630,30.29157] },
{ 'id': 27,
  'name': 'Новоадмиралтейский канал, д. 2 ',
  'task': 'Ограда напротив дома',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.93148,30.28348] },
{ 'id': 28,
  'name': 'Малый пр. В.О., д. 57 к. 3',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.94217,30.25712] },
{ 'id': 29,
  'name': 'Пл. Ленина, д. 1',
  'task': 'Заборчик перед домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.95337,30.35648] },
{ 'id': 30,
  'name': 'Кронверкский пр., д. 35',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.95703,30.31435] },
{ 'id': 31,
  'name': 'Академический переулок, д. 18',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.93650,30.28357] },
{ 'id': 32,
  'name': 'Памятник А. Нобелю в створе Пинского переулка',
  'task': 'Участок ограды набережной рядом с памятником',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.96084,30.33493] },
{ 'id': 33,
  'name': 'Ул. Рентгена, д. 8',
  'task': 'Участок ограды перед памятником Рентгену',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.96331,30.31693] },
{ 'id': 34,
  'name': 'Карповский мост',
  'task': 'Ограда моста',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.97041,30.30036] },
{ 'id': 35,
  'name': 'Каменный остров. 14 Каменноостровский мост',
  'task': 'Ограда моста',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro"],
  'coordinates': [59.97602,30.27783] },
{ 'id': 36,
  'name': 'Бобруйская ул., д. 5',
  'task': 'Небольшая ограда перед домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro"],
  'coordinates': [59.96425,30.35344] },
{ 'id': 37,
  'name': 'Басков пер., д. 3',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.93941,30.35637] },
{ 'id': 38,
  'name': 'Наб. р. Фонтанки, д. 105',
  'task': 'Участок ограды набережной напротив здания',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.92322,30.32085] },
{ 'id': 39,
  'name': '5-я Советская ул., д. 31-33',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.93338,30.37291] },
{ 'id': 40,
  'name': 'ул. Профессора Попова, д. 2 корп. 12',
  'task': 'Участок ограды со стороны набережной',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.97242,30.32844] },
{ 'id': 41,
  'name': 'Резная ул., д. 19/8',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.96581,30.28148] },
{ 'id': 42,
  'name': 'Пересечение Кемской и Динамовской ул.',
  'task': 'Столб знака "Пешеходный переход" ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.97352,30.26049] },
{ 'id': 43,
  'name': 'Наб. р. Мал. Невки, д. 1а',
  'task': 'Дерево рядом с домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.97904,30.30235] },
{ 'id': 44,
  'name': 'Выборгская наб., д. 51',
  'task': 'Пожарная лестница',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.97681,30.32931] },
{ 'id': 45,
  'name': 'Ставропольская ул., д. 10',
  'task': 'Дерево рядом с домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.94922,30.38549] },
{ 'id': 46,
  'name': 'Таврический сад',
  'task': 'Участок ограды в створе Парадной ул.',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.94375,30.37105] },
{ 'id': 47,
  'name': '3-я Красноармейская ул., д. 7',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.91453,30.31403] },
{ 'id': 48,
  'name': 'Социалистическая ул., д. 15',
  'task': 'Ограда перед домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.92186,30.34346] },
{ 'id': 50,
  'name': 'Самый западный железнодорожный мост через 1-й Муринский пр.',
  'task': 'Опора моста',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.98874,30.33718] },
{ 'id': 51,
  'name': 'Мост через Черную Речку в створе ул. Графова',
  'task': 'Ограда моста',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.98419,30.31017] },
{ 'id': 52,
  'name': 'Изгиб Чугунной ул. в районе д. 20',
  'task': 'Столб',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro"],
  'coordinates': [59.96979,30.35740] },
{ 'id': 53,
  'name': 'Ул. Жукова, д. 17а',
  'task': 'Каменный заборчик рядом с домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.96552,30.39215] },
{ 'id': 54,
  'name': 'Борисов мост',
  'task': 'Ограда моста',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.90911,30.28208] },
{ 'id': 55,
  'name': 'Участок наб. р. Фонтанки в створе Прядильного переулка',
  'task': 'Ограда',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.91648,30.29376] },
{ 'id': 56,
  'name': 'Угол Павлоградского пер., и ул. Черняховского',
  'task': 'Столб аншлага автобусного маршрута №24',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.91659,30.35636] },
{ 'id': 57,
  'name': 'Ул. Шевченко, д. 34',
  'task': 'Заборчик рядом с домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.94010,30.23902] },
{ 'id': 58,
  'name': 'Миргородская ул., д. 16',
  'task': 'Забор рядом с домом со стороны Кременчугской ул.',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.92504,30.37277] },
{ 'id': 59,
  'name': 'Сад Декабристов на В.О.',
  'task': 'Автобусная остановка со стороны пр. КИМа',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.95482,30.24260] },
{ 'id': 61,
  'name': 'Лабораторный пр., д. 16',
  'task': 'Столб рядом с домом',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.98103,30.38458] },
{ 'id': 63,
  'name': 'Балтийская ул., д. 36/9',
  'task': 'Забор рядом с домом со стороны Молодежного переулка',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.89971,30.28693] },
{ 'id': 64,
  'name': 'Изгиб Кожевенной линии в районе д. 5',
  'task': 'Водосточная труба на здании',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.92573,30.26650] },
{ 'id': 66,
  'name': 'Синопская наб., д. 34-36',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.93159,30.38973] },
{ 'id': 67,
  'name': 'Удельный парк. Железнодорожный мост над пешеходной дорожкой в юго-восточной части парка',
  'task': 'Деревце рядом с мостом',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.00543,30.31973] },
{ 'id': 68,
  'name': 'Задворная ул., д. 10',
  'task': 'Водосточная труба',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.89799,30.36032] },
{ 'id': 69,
  'name': 'Стык Сердобольской и Торжковской ул.',
  'task': 'Столб',
  'categories': ["run-light", "run-pro"],
  'coordinates': [59.99245,30.32203] },
{ 'id': 71,
  'name': 'Оконечность Серебряного пруда со стороны Институтского пр.',
  'task': 'Участок ограды парка',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [60.00344,30.34938] },
{ 'id': 72,
  'name': 'Уткин мост',
  'task': 'Ограда моста',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro"],
  'coordinates': [59.93394,30.42292] },
{ 'id': 74,
  'name': 'Ул. Примакова, д. 12',
  'task': 'Столб рядом с домом',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.86881,30.27704] },
{ 'id': 75,
  'name': 'Будапештская ул., д. 6',
  'task': 'Береза со стороны улицы',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.87321,30.36708] },
{ 'id': 77,
  'name': 'Пер. Матюшенко, д. 14',
  'task': 'Перила крыльца',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.87531,30.43929] },
{ 'id': 78,
  'name': 'Пересечение пр. Юрия Гагарина и Бассейной ул.',
  'task': 'Участок ограды Московского Парка Победы со стороны пр. Ю. Гагарина',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.86476,30.33657] },
{ 'id': 79,
  'name': 'Новомалиновская дорога, д. 6а. Железнодорожный мост напротив дома',
  'task': 'Перила лестницы',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.94836,30.44764] },
{ 'id': 81,
  'name': 'Озеро Долгое',
  'task': 'Ограда бетонной конструкции на берегу со стороны пр. Королева',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.01687,30.26013] },
{ 'id': 82,
  'name': 'Угол Невельской ул. и наб. р. Екатерингофки',
  'task': 'Столб',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.90468,30.25258] },
{ 'id': 83,
  'name': 'Гранитная ул., д. 8',
  'task': 'Столб напротив дома',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.91865,30.41802] },
{ 'id': 84,
  'name': 'Черниговская ул., д. 5',
  'task': 'Заборчик перед домом',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.89414,30.32341] },
{ 'id': 86,
  'name': 'Новороссийская ул., д. 52',
  'task': 'Столб',
  'categories': ["rider-light", "rider-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.99322,30.36540] },
{ 'id': 87,
  'name': 'Новоовсянниковская ул., д. 17',
  'task': 'Столб напротив дома',
  'categories': ["run-light", "run-pro", "roller-light", "roller-pro", "freak"],
  'coordinates': [59.88875,30.26245] },
{ 'id': 88,
  'name': 'Парк "Сосновка". Монумент защитникам Ленинградского неба',
  'task': 'Дерево позади монумента',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.01876,30.35072] },
{ 'id': 89,
  'name': 'Крестовский остров. Оконечность южного пруда, выходящая к Южной дороге',
  'task': 'Ель рядом с дорогой',
  'categories': ["run-light", "run-pro"],
  'coordinates': [59.96912,30.23363] },
{ 'id': 90,
  'name': 'Ул. Карпинского, д. 18. Участок бульвара напротив дома',
  'task': 'Дерево',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.00570,30.42167] },
{ 'id': 91,
  'name': 'Витебский пр., д. 47 к. 1',
  'task': 'Участок ограды детской площадки с южной стороны дома',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.85060,30.36294] },
{ 'id': 92,
  'name': 'Ул. Крупской, д. 13',
  'task': 'Пожарная лестница',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.89059,30.43379] },
{ 'id': 94,
  'name': 'Автобусная остановка "Анисимовская дорога, д. 41"',
  'task': 'Столб аншлага автобусной остановки',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.97371,30.44712] },
{ 'id': 95,
  'name': 'Ж.д. пл. "Озерки". Платформа "От Петербурга"',
  'task': 'Перила лестницы в южном конце платформы',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.03721,30.30339] },
{ 'id': 96,
  'name': 'Участок между дд. 13 и 15 по ул. Кржижановского',
  'task': 'Ограда',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.93041,30.48051] },
{ 'id': 97,
  'name': 'Пр. Луначарского, д. 92',
  'task': 'Пруд рядом с домом. Ограда мостика',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.03115,30.39555] },
{ 'id': 98,
  'name': 'Трамвайное кольцо маршрута №56 "Ул. Маршала Казакова" ',
  'task': 'Столб вначале разворотной петли',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.85985,30.22703] }]