[
{ 'id': 00,
  'name': 'Дворцовая площадь.',
  'task': 'Старт ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller-light", "roller-pro"],
  'coordinates': [59.939167,30.315833] },
{ 'id': 11,
  'name': 'Угол Менделеевской линии и Университетской наб.',
  'task': 'Участок ограды д. 2',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.94018,30.30131] },
{ 'id': 12,
  'name': 'Гороховая ул., д. 27',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.93057,30.31835] },
{ 'id': 13,
  'name': 'Миллионная ул., д 3',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.94580,30.33108] },
{ 'id': 14,
  'name': 'Мытнинская наб., д. 9',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.94825,30.30429] },
{ 'id': 15,
  'name': 'Наб. р. Фонтанки, д. 7',
  'task': 'Участок ограды набережной напротив дома ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.93771,30.34248] },
{ 'id': 21,
  'name': 'Биржевая линия, д. 18',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.94544,30.29436] },
{ 'id': 22,
  'name': 'Почтамтский мост',
  'task': 'Участок ограды ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.93048,30.30031] },
{ 'id': 23,
  'name': 'Апраксин пер., д. 8',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.92856,30.32595] },
{ 'id': 24,
  'name': 'Наб. р. Фонтанки.',
  'task': 'Участок ограды в створе ул. Чайковского ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.94639,30.33789] },
{ 'id': 25,
  'name': 'Наб. р. Фонтанки.',
  'task': 'Участок ограды в створе Итальянской ул. ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.93524,30.34349] },
{ 'id': 26,
  'name': 'Каменноостровский пр. Участок у съезда с Троицкого моста',
  'task': 'Участок ограды у Кронверкского пролива напротив Петропавловской крепости ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.95243,30.32249] },
{ 'id': 27,
  'name': 'Ул. Чайковского, д. 47',
  'task': 'Небольшая ограда перед домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.94628,30.35668] },
{ 'id': 28,
  'name': 'Ораниенбаумская ул., д. 13',
  'task': 'Участок ограды рядом с домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.95998,30.29962] },
{ 'id': 30,
  'name': 'Таврическая ул., д. 35',
  'task': 'Участок ограды Таврического сада напротив дома ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.94697,30.37809] },
{ 'id': 31,
  'name': 'Ул. Рылеева, д. 11',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.94239,30.35459] },
{ 'id': 32,
  'name': 'Дегтярная ул., д. 40',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.93678,30.37648] },
{ 'id': 33,
  'name': 'Угол Аптекарского пр. и наб. р. Карповки',
  'task': 'Участок ограды Ботанического сада со стороны набережной ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.96821,30.31882] },
{ 'id': 34,
  'name': 'Ул. Комсомола, д. 4',
  'task': 'Участок ограды перед домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.95522,30.36822] },
{ 'id': 35,
  'name': 'Ул. Марата, д. 44',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.92508,30.35165] },
{ 'id': 36,
  'name': 'Ул. Жуковского, д. 53',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.93575,30.36086] },
{ 'id': 37,
  'name': 'Пр. Римского-Корсакова, д. 8',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.92424,30.30594] },
{ 'id': 38,
  'name': 'Северо-восточная оконечность парка ЛТА',
  'task': 'Участок ограды со стороны Новороссийской ул. ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.99459,30.35420] },
{ 'id': 39,
  'name': 'Социалистическая ул., д. 10',
  'task': 'Ограда перед домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.92321,30.34151] },
{ 'id': 40,
  'name': 'Угол Смольной наб. и ул. Смольного',
  'task': 'Фонарный столб ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.95166,30.39893] },
{ 'id': 41,
  'name': 'Мало-Петровский мост через р. Ждановка',
  'task': 'Участок ограды с западной стороны ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.96103,30.27150] },
{ 'id': 42,
  'name': 'Лопухинский сад.',
  'task': 'Участок ограды в створе Уфимской ул. ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.97669,30.30848] },
{ 'id': 43,
  'name': 'Лодейнопольская ул., д. 2',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.96542,30.29106] },
{ 'id': 44,
  'name': 'Ул. Комиссара Смирнова',
  'task': 'Участок ограды между дд. 13 и 15 ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.96249,30.35003] },
{ 'id': 45,
  'name': 'Климов пер., д. 5',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.91830,30.29434] },
{ 'id': 46,
  'name': '7-я Красноармейская ул., д. 18',
  'task': 'Участок ограды рядом с домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.91149,30.31193] },
{ 'id': 47,
  'name': 'Пр. Металлистов, д. 36',
  'task': 'Деревце перед домом ',
  'categories': ["roller", "rider-light", "rider-pro"],
  'coordinates': [59.95189,30.42053] },
{ 'id': 48,
  'name': 'Лиговский пр., д. 275 к. 1',
  'task': 'Автобусная остановка рядом с домом. Столб ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.90400,30.34117] },
{ 'id': 49,
  'name': 'Синопская наб., д. 24',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.92881,30.38803] },
{ 'id': 50,
  'name': '15-я линия В.О., д. 22',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.93840,30.26981] },
{ 'id': 51,
  'name': 'Большеохтинский мост. Южная сторона',
  'task': 'Участок ограды со стороны Свердловской набережной ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.94270,30.40479] },
{ 'id': 52,
  'name': 'Кондратьевский пр., д. 40 к. 5',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.96880,30.38116] },
{ 'id': 53,
  'name': 'Новолитовская ул., д. 10',
  'task': 'Дерево перед домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.98165,30.35630] },
{ 'id': 54,
  'name': 'Тамбовская ул., д. 46',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.91021,30.35286] },
{ 'id': 55,
  'name': 'Наб. Обводного канала, д. 39',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.91502,30.37170] },
{ 'id': 56,
  'name': 'Ул. Красуцкого, д. 3',
  'task': 'Ограда сквера перед домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.90291,30.31566] },
{ 'id': 57,
  'name': 'Екатерингофский мост',
  'task': 'Участок ограды с северной стороны ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.91286,30.26194] },
{ 'id': 60,
  'name': 'Угол Кемской ул. и ул. Рюхина',
  'task': 'Участок ограды со стороны парка ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.97350,30.25816] },
{ 'id': 61,
  'name': 'Угол Институтского пер. и Сочинской ул.',
  'task': 'Столб ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.99270,30.33548] },
{ 'id': 62,
  'name': 'Бестужевская ул., д. 20 к. 2',
  'task': 'Дерево рядом с домом ',
  'categories': ["rider-light", "rider-pro", "roller"],
  'coordinates': [59.98534,30.40222] },
{ 'id': 63,
  'name': 'Угол Западной и Санаторной аллей',
  'task': 'Участок ограды ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.97500,30.28808] },
{ 'id': 64,
  'name': 'Ул. Стасовой, д. 6',
  'task': 'Ограда со стороны дома №8 ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.96857,30.43352] },
{ 'id': 65,
  'name': 'Ул. Шателена, д. 20',
  'task': 'Водосточная труба ',
  'categories': ["rider-light", "rider-pro", "roller"],
  'coordinates': [60.00515,30.36013] },
{ 'id': 66,
  'name': 'Ул. Маршала Говорова, д. 40',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.89435,30.28404] },
{ 'id': 67,
  'name': 'Таллинская ул., д. 22',
  'task': 'Дерево рядом с домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.92533,30.41704] },
{ 'id': 68,
  'name': 'Нарвский пр.',
  'task': 'Информационный щит в створе Бумажной ул. ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.90318,30.27398] },
{ 'id': 69,
  'name': 'Ул. Профессора Качалова, д. 11',
  'task': 'Фонарный столб рядом с домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.91126,30.39288] },
{ 'id': 70,
  'name': 'Армашевский мост',
  'task': 'Участок ограды с северо-восточной стороны ',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.96191,30.46888] },
{ 'id': 71,
  'name': 'Пр. Ударников, д. 49 к. 1',
  'task': 'Ограда рядом с домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.95553,30.49170] },
{ 'id': 72,
  'name': 'Ул. Бутлерова, д. 8',
  'task': 'Автобусная остановка напротив дома. Столб ',
  'categories': ["rider-light", "rider-pro", "roller"],
  'coordinates': [60.00067,30.39580] },
{ 'id': 73,
  'name': 'Ярославский пр., д. 9',
  'task': 'Ограда рядом с домом со стороны Эммануиловской ул. ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [60.00996,30.32315] },
{ 'id': 74,
  'name': 'Благодатная ул., д. 38',
  'task': 'Небольшой заборчик перед домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.87628,30.33231] },
{ 'id': 75,
  'name': 'Октябрьская наб., д. 26 к. 1',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.90750,30.43065] },
{ 'id': 76,
  'name': 'Мост через р. Оккервиль недалеко от д. 15 к. 5 по пр. Пятилеток',
  'task': 'Ограда ',
  'categories': ["rider-light", "rider-pro", "roller"],
  'coordinates': [59.92671,30.45605] },
{ 'id': 77,
  'name': 'Трубопроводная эстакада через трамвайные пути на Корабельной ул.',
  'task': 'Опора, ближайшая к путям ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.87657,30.24705] },
{ 'id': 78,
  'name': 'Угол ул. Новостроек и Автовской ул.',
  'task': 'Ближайшая опора ЛЭП ',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.87317,30.27428] },
{ 'id': 79,
  'name': 'Коломяжский пр. Монумент на месте дуэли А.С. Пушкина',
  'task': 'Дерево неподалеку ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.99502,30.30173] },
{ 'id': 80,
  'name': 'Ул. Руставели. Трамвайная остановка "ул. Верности"',
  'task': 'Остановочный павильон ',
  'categories': ["rider-light", "rider-pro", "roller"],
  'coordinates': [59.99594,30.43724] },
{ 'id': 81,
  'name': 'Угол Арктической ул. и Поклонногорской ул.',
  'task': 'Столб ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [60.02714,30.31266] },
{ 'id': 82,
  'name': 'Аллея Поликарпова, д. 8',
  'task': 'Береза на участке бульвара напротив дома ',
  'categories': ["rider-light", "rider-pro", "roller"],
  'coordinates': [60.00744,30.28862] },
{ 'id': 83,
  'name': 'Угол ул. Ак. Байкова и ул. Вавиловых',
  'task': 'Столб ',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.02283,30.39311] },
{ 'id': 84,
  'name': 'Парк, ограниченный ул. Ивана Фомина, пр. Просвещения, ул. Есенина и Сиреневым бульваром',
  'task': 'Дерево недалеко от северной оконечности пруда ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [60.05406,30.34818] },
{ 'id': 85,
  'name': 'Ул. Шотмана, д. 14, к. 1',
  'task': 'Заборчик со стороны д. 12-1 ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.90179,30.48238] },
{ 'id': 86,
  'name': 'Трамвайный пр., д. 13, к. 1',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.85619,30.26119] },
{ 'id': 87,
  'name': 'Пруд в парке Авиаторов',
  'task': 'Дерево на берегу пруда со стороны Кузнецовской ул. ',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [59.86970,30.29972] },
{ 'id': 88,
  'name': 'Автобусная остановка м-та №72 "ул. Типанова"',
  'task': 'Остановочный павильон ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.85725,30.35815] },
{ 'id': 90,
  'name': 'Угол Хасанской ул. и Белорусской ул.',
  'task': 'Забор ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.93559,30.50043] },
{ 'id': 91,
  'name': 'Ситцевая ул., д. 17-2',
  'task': 'Зеленый забор площадки рядом с домом ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.99990,30.23770] },
{ 'id': 92,
  'name': 'Угол ул. Маршала Новикова и Автобусной ул.',
  'task': 'Остановка на Автобусной ул. Столб ',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.02752,30.27473] },
{ 'id': 93,
  'name': 'Тимуровская ул., д. 28',
  'task': 'Забор детского сада рядом с домом ',
  'categories': ["rider-light", "rider-pro"],
  'coordinates': [60.04211,30.41428] },
{ 'id': 95,
  'name': 'Ул. Цимбалина, д. 38',
  'task': 'Дерево рядом с трансформаторной будкой ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.88416,30.42684] },
{ 'id': 96,
  'name': 'Ул. Орджоникидзе, д. 8',
  'task': 'Водосточная труба ',
  'categories': ["run-light", "run-pro", "rider-light", "rider-pro", "roller"],
  'coordinates': [59.84453,30.32563] }
]